### ISSUE TITLE
configure file is missing

### ISSUE THREAD

**Issue by llamafilm** [scottjg/ipmitool#2]
The configure file is missing, so how do I compile this?

**Comment by scottjg** [comment]
> The configure file is missing

i don't think it is
<img width="465" alt="screen shot 2018-05-04 at 3 52 56 pm" src="https://user-images.githubusercontent.com/118412/39656232-3cc54ab2-4fb3-11e8-8312-f037faab48b7.png">

**Comment by llamafilm** [comment]
Sorry, I commented on the wrong project, too many tabs open! Please ignore.
